### ISSUE TITLE
Allow change background color

### ISSUE THREAD

**Issue by tanlucvo** [baronha/ting#1]
Cho đổi background được khum bác ơi ^-^

**Comment by baronha** [comment]
Mình sẽ thêm nó vào [Todo](https://github.com/baronha/ting/blob/main/README.md#to-do). 
Thực ra trước khi release thì mình có thử xem thay đổi `backgroundColor` được không. `Android` thì hoàn toàn được nhưng với iOS đang sử dụng một blur view làm background thì việc thay đổi `backgoundColor` chưa khả thi trên `iOS`. Trong tương lai sẽ có nhé. Vì đây là một tuỳ biến mà mình cần trong việc triển khai `dynamic theme` ở nhiều dự án

**Comment by baronha** [comment]
Có tin zui đêyy bro êi. Đã thêm option backgroundColor trên cả `Android` và `iOS` ở version @1.0.2 nhé. Thân gửi

https://github.com/baronha/ting/assets/23580920/9335796e-c1d8-4497-bd2f-03090632b56b
