### ISSUE TITLE
Not working expo

### ISSUE THREAD

**Issue by tuongmac0101** [baronha/ting#13]
I tried everything but it still doesn't work in Expo. Please

**Comment by tuongmac0101** [comment]
![Screenshot 2023-08-26 at 11 33 29](https://github.com/baronha/ting/assets/60650917/430b6f6a-f964-49f4-8db9-e9f87292d81a)

**Comment by baronha** [comment]
If you want to use Expo. [Burnt](https://github.com/nandorojo/burnt) is the solution for you.
I mentioned that in the [README](https://github.com/baronha/ting#installation)

**Comment by tuongmac0101** [comment]
> 

tks bro

**Comment by mrevanzak** [comment]
is there any reason why not supporting expo? is it not possible or what?
