### ISSUE TITLE
'ting-Swift.h' file not found

### ISSUE THREAD

**Issue by kapilkarda** [baronha/ting#15]
![Screenshot 2023-10-31 at 2 52 37 PM](https://github.com/baronha/ting/assets/4336836/56411448-fde8-4293-8b6b-914cd9b1a854)

i am stuck in this issue isn't not fixing can anyone fix this

**Comment by agrawalshubham1012** [comment]
Can you give me update regarding this task i need it

**Comment by longnguyen2508** [comment]
Got the same error while building project

**Comment by baronha** [comment]
Did you guys use New Arch for the project?

**Comment by zcmgyu** [comment]
Possibly, the problem might stem from the `use_frameworks! :linkage => :static` entry in the `Podfile`. This configuration may currently not be compatible with Swift projects. Check out the discussion on [GitHub](https://github.com/reactwg/react-native-new-architecture/discussions/129) for more details.

**Comment by 4cc3ssX** [comment]
Just a workaround who is using this library with `use_frameworks!` enabled, please change `#import <ting-Swift.h>` to `#import <Ting/Ting-Swift.h>`. You're done and successfully built with `use_frameworks! :linkage => :static` enabled!🎉

```patch
diff --git a/ios/Ting.mm b/ios/Ting.mm
index 2ae7778f02d1a42fc029761a27f0f7c4d6225f85..3673dcf75eb95044891ae3a44c906a0e644a9e78 100644
--- a/ios/Ting.mm
+++ b/ios/Ting.mm
@@ -1,6 +1,6 @@
 #import "Ting.h"
 
-#import <ting-Swift.h>
+#import <Ting/Ting-Swift.h>
 
 @implementation Ting
```
