### ISSUE TITLE
Hi! I see u set 13 as minimun, which will deny iPhone 5s, any reason?

### ISSUE THREAD

**Issue by Acetyld** [baronha/ting#2]
Specs satisfying the `Ting (from `../node_modules/@baronha/ting`)` dependency were found, but they required a higher minimum deployment target.
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "Ting":
  In Podfile:
    Ting (from `../node_modules/@baronha/ting`)

Specs satisfying the `Ting (from `../node_modules/@baronha/ting`)` dependency were found, but they required a higher minimum deployment target.

**Comment by arunabhverma** [comment]
> Specs satisfying the `Ting (from `../node_modules/@baronha/ting`)` dependency were found, but they required a higher minimum deployment target. Couldn't install Pods. Updating the Pods project and trying again... Command `pod install` failed. └─ Cause: CocoaPods could not find compatible versions for pod "Ting": In Podfile: Ting (from `../node_modules/@baronha/ting`)
> 
> Specs satisfying the `Ting (from `../node_modules/@baronha/ting`)` dependency were found, but they required a higher minimum deployment target.

Facing the same issue

**Comment by Acetyld** [comment]
Yup same, even when setting it to 13 no success

**Comment by arunabhverma** [comment]
> Yup same, even when setting it to 13 no success

you can try this one https://github.com/nandorojo/burnt
same library

**Comment by Acetyld** [comment]
> > Yup same, even when setting it to 13 no success
> 
> you can try this one https://github.com/nandorojo/burnt same library

Yhea i know, we dont want to install expo (yet), we plan on done a full rebuild some day but for now we just need a toast library, this one i am still having hope for, love this guy

**Comment by baronha** [comment]
I'm modifying the above lines of code to be suitable for versions lower than iOS 13. Probably tomorrow there will be a new version for iOS 12+.

<img width="866" alt="Screen Shot 2023-07-11 at 13 45 48" src="https://github.com/baronha/ting/assets/23580920/cc107cf1-ac2b-48a9-9dcb-1ecc344214c5">

**Comment by baronha** [comment]
> > Yup same, even when setting it to 13 no success
> 
> you can try this one https://github.com/nandorojo/burnt same library

Burnt require iOS 13.0+. You can see [ios/Burnt.podspec](https://github.com/nandorojo/burnt/blob/9266b45e2512aac23166582399eddd9d96899bde/ios/Burnt.podspec#L13). 
And there is also an [issue](https://github.com/nandorojo/burnt/issues/20#issuecomment-1602036401) about the above that has been explained by nandorojo.

**Comment by baronha** [comment]
You can try 1.0.3 right now☄️☄️☄️ !!

**Comment by Acetyld** [comment]
> You can try 1.0.3 right now☄️☄️☄️ !!

Perfect! Dont forget the Github release =)
