### ISSUE TITLE
'onScroll' overrides nothing

### ISSUE THREAD

**Issue by loczippo** [baronha/ting#23]
.../node_modules/@baronha/ting/android/src/main/java/com/ting/TingModule.kt:83:15 'onScroll' overrides nothing FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':baronha_ting:compileDebugKotlin'. > A 
failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error

**Comment by loczippo** [comment]
@baronha

**Comment by mduc-dev** [comment]
hello @loczippo, You can temporarily fix it as follows **override fun onScroll(e1: MotionEvent?, e2: MotionEvent, distanceX: Float, distanceY: Float): Boolean**
I just had this same error this afternoon, and tried this way it works in **Android API 34**

**Comment by RattyJhay** [comment]
> hello @loczippo, You can temporarily fix it as follows **override fun onScroll(e1: MotionEvent?, e2: MotionEvent, distanceX: Float, distanceY: Float): Boolean** I just had this same error this afternoon, and tried this way it works in **Android API 34**

Your explaination isn't clear. How do you override funScroll. I'm having the same error building with expo, can you be specific on how to fix it.

**Comment by loczippo** [comment]
> > hello @loczippo, You can temporarily fix it as follows **override fun onScroll(e1: MotionEvent?, e2: MotionEvent, distanceX: Float, distanceY: Float): Boolean** I just had this same error this afternoon, and tried this way it works in **Android API 34**
> 
> Your explanation isn't clear. How do you override **fun onScroll**. I'm having the same error building with expo, can you be specific on how to fix it.

let delete function onScroll in nodes_module of ting

**Comment by VanDinh18** [comment]
@loczippo  You could use [patch package](https://github.com/ds300/patch-package). You go to TingModule.kt on Android, update it same below code `override fun onScroll(e1: MotionEvent?, e2: MotionEvent, distanceX: Float, distanceY: Float): Boolean {`
