### ISSUE TITLE
Build Error: 'ReactCommon/RCTTurboModule.h' file not found when Building with Xcode 16 and iOS Simulator 18

### ISSUE THREAD

**Issue by 4cc3ssX** [baronha/ting#36]
## Description
I'm experiencing a build issue when compiling React Native app for iOS. The error message indicates that `'ReactCommon/RCTTurboModule.h' file is not found`. This might be related to a React Native codegen issue.

## Error
```
'ReactCommon/RCTTurboModule.h' file not found
```

## Environment
- [x] Xcode Version: 16
- [x] iOS Simulator Target: 18
- [x] New Architecture: Enabled
- [x] `use_frameworks! :linkage => linkage.to_sym`
- [x] React Native version **0.75.3**

## Steps to Reproduce
- Enable the new architecture in the React Native project.
- Install `@baronha/ting` version `1.2.2`.
- Set `use_frameworks! :linkage => linkage.to_sym` in the Podfile.
- Build the app using Xcode **16** targeting iOS Simulator **18**.

<img width="901" alt="Screenshot 2567-09-21 at 9 39 16 PM" src="https://github.com/user-attachments/assets/ade6dd34-85e5-4e9d-8d07-e0caebb3dc00">

**Comment by ISnowFoxI** [comment]
I have the same issue, 
- React Native v75.3

**Comment by limintao** [comment]
I have the same issue,

React Native v76.0
new arch enabled

**Comment by 4cc3ssX** [comment]
This issue has been fixed on this PR (#38) and I'm closing for now.🚀

**Comment by baronha** [comment]
Release 1.2.3 🤘🤘🤘
Thank Ryam @4cc3ssX
