### ISSUE TITLE
 ERROR  TypeError: undefined is not a function, js engine: hermes

### ISSUE THREAD

**Issue by Acetyld** [baronha/ting#4]
It seems that the alert is not working on IOS, i am running without new architecture.

```
import { alert } from '@baronha/ting';
alert({
     title: 'Done 😎',
     message: 'Successful!!',
});
```
```
    "@baronha/ting": "^1.0.3",
    "react-native": "0.71.4",
```

![Screenshot 2023-07-12 at 09 44 09](https://github.com/baronha/ting/assets/55088242/19c2baef-73a7-49bc-8afb-ecb16adc931f)

**Comment by baronha** [comment]
I will fix it. Wait a minute

**Comment by baronha** [comment]
@Acetyld I solved it
