### ISSUE TITLE
Ability to set default background/text color.

### ISSUE THREAD

**Issue by Acetyld** [baronha/ting#7]
In our app our darkmode background is almost identical to the one that is used by default in toast(), would there be a possible to set a default for the toast/alert?
![Screenshot 2023-07-12 at 19 22 00](https://github.com/baronha/ting/assets/55088242/2db3190f-0c66-413e-bcbd-c9f3cacb7df7)

**Comment by baronha** [comment]
Yup. You can use `backgroundColor`. 
In the next version, I will allow you to set default options when starting the application (This does not affect the performance because it is very light)

**Comment by Acetyld** [comment]
```
export const useThemeInit = () => {
  const { colors } = useTheme<Theme>();
  useEffect(() => {
    const initOption = {
      toast: {
        titleColor: colors.text,
        messageColor: colors.text6,
        backgroundColor: colors.background9,
      },
      alert: {
        titleColor: colors.text,
        messageColor: colors.text6,
        backgroundColor: colors.background9,
      },
    };
    setup(initOption);
  }, [colors.background9, colors.text, colors.text6]);
};

```

@baronha very cool! It works perfect =)

**Comment by baronha** [comment]
@Acetyld Glad to have helped with a tiny part of your project 😆😆😆
